### ISSUE TITLE
Food for though: Assume local git clone to shorten URLs in shell examples 

### ISSUE THREAD

**Issue by luebken** [mhausenblas/kbe#7]
The current examples grep the k8s resources straight from Github (https://raw.githubusercontent.com/mhausenblas/kbe/master/ ...). This makes it convenient since no other setup is required. At the same time it makes hard to understand which yaml is used. Which made me always scroll to the right.

[Here](https://github.com/luebken/kbe/tree/assume-git-clone) is a simple example that assumes a local copy:   

![screen shot 2017-05-15 at 12 43 34](https://cloud.githubusercontent.com/assets/53055/26054428/d2bdcc46-396c-11e7-930c-84a2062011c0.png)

For me easier to read. At the same time I want the yamls open in my editor anyway to understand / check whats I am going to start next.

**Comment by mhausenblas** [comment]
Thanks @luebken for this suggestion. I'll look into it.

**Comment by lexsys27** [comment]
Another idea is to include `yaml` files into text like it is done in "Kubernetes the hard way" course. This approach allows me to review the configuration before running the commands.

```
cat > pod.yaml <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: twocontainers
spec:
  containers:
  - name: sise
    image: mhausenblas/simpleservice:0.5.0
    ports:
    - containerPort: 9876
  - name: shell
    image: centos:7
    command:
      - "bin/bash"
      - "-c"
      - "sleep 10000"
EOF
```
And thank you for the course, @mhausenblas ! I have just passed it and it is awesome intro to k8s.
